include(${CMAKE_CURRENT_LIST_DIR}/epaper/config.cmake)

list(APPEND DRIVER_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/tft.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_ili9341.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_ili9481.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_ili9486.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_ili9488.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_ssd1306.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_ssd1327.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_st7735s.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_st7789v.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_st7796u.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_st77916.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_gc9a01.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_r61581.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_st6201.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_st7305.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_st7576.c
    ${CMAKE_CURRENT_LIST_DIR}/tft_1p5623.c
)
