list(APPEND DRIVER_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/indev.c
    ${CMAKE_CURRENT_LIST_DIR}/cst816d.c
    ${CMAKE_CURRENT_LIST_DIR}/gt911.c
    ${CMAKE_CURRENT_LIST_DIR}/tsc2007.c
    ${CMAKE_CURRENT_LIST_DIR}/ft6236.c
)
